services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $projectDir: '%kernel.project_dir%'
    
    InspiredMinds\ContaoNewsArchiving\:
        resource: ../src
        exclude: ../src/{ContaoManager,DependencyInjection,ContaoNewsArchivingBundle.php}
